FROM python:3.10.7

WORKDIR /RWR

# installing essential packages
RUN pip install networkx==2.8
RUN pip install numpy==1.24.3
RUN pip install scipy==1.10.1

RUN wget https://raw.githubusercontent.com/Reed-CompBio/random-walk-with-restart/31c61c1dae1c04c6b5c228ca7ddbf4c4cedabd4f/random_walk.py