# The length of the hash used to identify a parameter combination
hash_length: 7

# If true, use Singularity instead of Docker
# Singularity support is only available on Unix
singularity: false

algorithms:
        - name: "pathlinker"
          params:
                include: true
                directed: false
                run1:
                    k:
                      - 30
                      - 50
                      - 100
                      - 200
                      - 500
                      - 700
                      - 1000
                      - 1500
                      - 2000
                      - 3000

        - name: "rwr"
          params:
                include : true
                directed : false
                run1:
                    w:
                      - 0.25
                      - 0.3
                      - 0.35
                      - 0.4
                      - 0.45
                    df:
                      - 0.75
                      - 0.8
                      - 0.85
                      - 0.9
                      - 0.95
                    threshold:
                      - 0.0001
                      - 0.0002
                      - 0.0003
                      - 0.0004

        # - name: "tiedie"
        #   params:
        #         include: true
        #         directed: false

datasets:
     -
       label: cell-cell-fusion
       node_files: ["alternative_source_gene.txt", "cell_target_gene.txt"]
       # DataLoader.py can currently only load a single edge file, which is the primary network
       edge_files: ["flybase_interactome.txt"]
       # Placeholder
       other_files: []
       # Relative path from the spras directory
       data_dir: "input"
     -
       label: muscle-development
       node_files: ["alternative_source_gene.txt", "muscle_target_gene.txt"]
       # DataLoader.py can currently only load a single edge file, which is the primary network
       edge_files: ["flybase_interactome.txt"]
       # Placeholder
       other_files: []
       # Relative path from the spras directory
       data_dir: "input"

reconstruction_settings:
  locations:
    reconstruction_dir: output/amigo2
  run: true
analysis:
  graphspace:
    include: false
  summary:
    include: true
  ml:
    include: false
