# The length of the hash used to identify a parameter combination
hash_length: 7

# If true, use Singularity instead of Docker
# Singularity support is only available on Unix
singularity: false

algorithms:
  -
    name: omicsintegrator1
    params:
      directed: false
      include: true
      run1:
        b:
          - 0.55
          - 2
          - 10
        d:
          - 10
        g:
          - 1e-3
        r:
          - 0.01
        w:
          - 0.1
        mu:
          - 0.008
  -
    name: omicsintegrator2
    params:
      directed: false
      include: true
      run1:
        b:
          - 4
        g:
          - 0
      run2:
        b:
          - 2
        g:
          - 3

datasets:
  -
    data_dir: input
    edge_files:
      - flybase_interactome.txt
    label: flybase
    node_files:
      - source_gene.txt
    other_files: []
reconstruction_settings:
  locations:
    reconstruction_dir: FlyBase
  run: true
analysis:
  graphspace:
    include: false
  summary:
    include: false
  ml:
    include: false
