# The length of the hash used to identify a parameter combination
hash_length: 7

# If true, use Singularity instead of Docker
# Singularity support is only available on Unix
singularity: false

algorithms:
  -
    name: omicsintegrator1
    params:
      directed: false
      include: true
      run1:
        b:
          - 4
          - 8
          - 10
          - 12
          - 15
        d:
          - 10
        g:
          - 1e-3
        r:
          - 0
        w:
          - 1
          - 1.5
          - 2
          - 2.5
          - 3
        mu:
          - 0.0001
          - 0.0003
          - 0.0005
          - 0.0007

datasets:
  -
    data_dir: input
    edge_files:
      - flybase_interactome.txt
    label: flybase
    node_files:
      - source_gene.txt
    other_files: []
reconstruction_settings:
  locations:
    reconstruction_dir: output/flybase
  run: true
analysis:
  graphspace:
    include: false
  summary:
    include: true
  ml:
    include: false
